<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AllowanceRateSeeder extends Seeder
{
    /**
     * Seed the application's allowance rates.
     */
    public function run(): void
    {
        DB::table('allowance_rates')->insert([
            ['country' => 'Bosnia and Herzegovina', 'rate_km' => 0, 'rate_bam' => 45.00, 'region' => 'BiH', 'is_default' => false, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Albania', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Andorra', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Armenia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Austria', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Azerbaijan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Belarus', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Belgium', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Bulgaria', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Croatia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Cyprus', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Czech Republic', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Denmark', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Estonia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Finland', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'France', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Georgia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Germany', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Greece', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Hungary', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Iceland', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Ireland', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Italy', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Kazakhstan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Kosovo', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Kyrgyzstan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Latvia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Liechtenstein', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Lithuania', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Luxembourg', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Malta', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Moldova', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Monaco', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Montenegro', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Netherlands', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'North Macedonia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Norway', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Poland', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Portugal', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Romania', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Russia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'San Marino', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Serbia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Slovakia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Slovenia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Spain', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Sweden', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Switzerland', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Turkey', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Ukraine', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'United Kingdom', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Australia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'New Zealand', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Afghanistan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Bangladesh', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Bhutan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Brunei', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Cambodia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'China', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'India', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Indonesia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Japan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Laos', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Malaysia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Maldives', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Mongolia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Myanmar', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Nepal', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Pakistan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Philippines', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Singapore', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'South Korea', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'North Korea', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Sri Lanka', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Thailand', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Timor-Leste', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Vietnam', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Yemen', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'United Arab Emirates', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Saudi Arabia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Oman', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Qatar', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Bahrain', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Kuwait', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Jordan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Lebanon', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Israel', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Iraq', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Iran', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Syria', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Egypt', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Libya', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Tunisia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Algeria', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Morocco', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Mauritania', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Mali', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Niger', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Chad', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Sudan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'South Sudan', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => Now(), 'updated_at' => now()],
            ['country' => 'Eritrea', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Djibouti', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Somalia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Ethiopia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Kenya', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Uganda', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Tanzania', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Rwanda', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Burundi', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Democratic Republic of the Congo', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Republic of the Congo', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Angola', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Zambia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Zimbabwe', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Botswana', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Namibia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'South Africa', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Lesotho', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Eswatini', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Madagascar', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Mozambique', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Malawi', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Seychelles', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Mauritius', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Cape Verde', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Senegal', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Guinea', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Guinea-Bissau', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Sierra Leone', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Liberia', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Ghana', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Côte d\'Ivoire', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Togo', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Benin', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Cameroon', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Central African Republic', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Gabon', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Equatorial Guinea', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'São Tomé and Príncipe', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Cuba', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Haiti', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Dominican Republic', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Jamaica', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Trinidad and Tobago', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Barbados', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Bahamas', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Panama', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Costa Rica', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
            ['country' => 'Nicaragua', 'rate_km' => 0, 'rate_bam' => 90.00, 'region' => 'International', 'is_default' => true, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
